config/routes.rb
Rails.application.routes.draw do
	devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'books#top'
  get "home/about" => 'books#about'
  resources :users, only: [:show, :index, :edit, :update]
  resources :books, only: [:new, :index, :create, :show, :edit, :destroy, :update ] do
  	resources :post_comments, only: [:create, :destroy]
  	resource :favorites, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

	belongs_to :user
	has_many :post_comments, dependent: :destroy
	has_many :favorites,dependent: :destroy
	def favorited_by?(user)
        favorites.where(user_id: user.id).exists?
    end
	validates :title,
		presence: true
	validates :body,
		presence: true,
	  	length: { minimum: 1, maximum: 200 }

end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :book

	validates_uniqueness_of :book_id, scope: :user_id
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
	belongs_to :user
	belongs_to :book
	validates :comment,
		presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books,dependent: :destroy
  attachment :profile_image
  has_many :post_commenrs, dependent: :destroy
  has_many :favorites,dependent: :destroy

  validates :name,
	  uniqueness: { case_sensitive: :false },
	  length: { minimum: 2, maximum: 20 }
  validates :introduction,
	  uniqueness: { case_sensitive: :false },
	  length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	 before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :name])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end

  def after_sign_out_path_for(reosuce)
    flash[:notice] = 'Signed out successfully.'
    root_path
  end

  def after_sign_in_path_for(reosuce)
    flash[:notice] = 'Welcome! You have sign in successfully.'
  	user_path(resource)
  end

  def after_sign_up_path_for(reosuce)
    flash[:notice] = 'Welcome! You have signed up successfully.'
    user_path(resource)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!, only: [:index, :create, :show, :edit, :update, :destroy]

	def index
		@book = Book.new
		@books = Book.all
	end

	def create
		@book = Book.new(book_params)
		@book.user_id = current_user.id
		if @book.save
		   flash[:notice] = 'You have creatad book successfully.'
		   redirect_to book_path(@book.id)
		else
			@books = Book.all
			render :index
		end
	end

	def show
		@book = Book.new
		@books = Book.find(params[:id])
		@comment = PostComment.new
	end

	def edit
		@book = Book.find(params[:id])
		if @book.user == current_user
			render :edit
		else
			redirect_to books_path
		end
	end

	def update
		@book = Book.find(params[:id])
		if @book.update(book_params)
		   flash[:notice] = 'You have updated book successfully.'
		   redirect_to book_path(@book.id)
		else
			render :edit
		end
	end

	def destroy
		@book = Book.find(params[:id])
		@book.destroy
		redirect_to books_path
	end

	private
    def book_params
		params.require(:book).permit(:title, :body)
	end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

	def create
    @book = Book.find(params[:book_id])
    favorite = Favorite.new
    favorite.book_id = @book.id
    favorite.user_id = current_user.id
    favorite.save
	end

	def destroy
    @book = Book.find(params[:book_id])
    favorite = Favorite.find_by( user_id: current_user.id, book_id: @book.id)
    favorite.destroy
	end

	private
  def set_book
    book = Book.find(params[:book_id])
  end

end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController

	def create
		book = Book.find(params[:book_id])
	    comment = PostComment.new(post_comment_params)
	    comment.user_id = current_user.id
	    comment.book_id = book.id
	    comment.save
	    redirect_to book_path(book)
	end

	def destroy
		PostComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    	redirect_to book_path(params[:book_id])
	end


	private
	def post_comment_params
		params.require(:post_comment).permit(:comment)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!


  def show
   @user = User.find(params[:id])
  	@book = Book.new
  	@books = @user.books
  end

  def index
  	@users = User.all
    @book = Book.new
  end

  def edit
  	@user = User.find(params[:id])
    if @user.id == current_user.id
      render :edit
    else
      redirect_to user_path(current_user.id)
    end
  end

  def update
  	@user = User.find(params[:id])
    if @user.update(user_params)
       flash[:notice] ='You have updated user successfully.'
       redirect_to user_path(@user.id)
    else
      render :edit
    end
  end


  private
    def user_params
		params.require(:user).permit(:name, :introduction, :profile_image)
	 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">
	<% if @book.errors.any? %>
		<p><%= @book.errors.count %>error prohibited this obj from being saved: </p>
		<ul>
			<% @book.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	<% end %>

	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<h1>Editing Book</h1>
			<%= form_for(@book) do |f| %>
			<div class="field row">
				<label>Title</label>
				<%= f.text_field :title, class:"col-xs-12 book_title" %>
			</div>
			<div class="field row">
				<label>Opinion</label>
				<%= f.text_area :body, class:"col-xs-12 book_body" %>
			</div>
			<div class="actions row">
				<%= f.submit "Update Book" , class:"btn btn-primary col-xs-12" %>
			</div>
			<% end %>
			<%= link_to "Show", book_path(@book) %>|<%= link_to "Back", books_path %>
		</div>
	</div>
</div>

app/views/books/index.html.erb
<div class="container">
	<% if @book.errors.any? %>
		<p><%= @book.errors.count %>error prohibited this obj from being saved: </p>
		<ul>
			<% @book.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	<% end %>

	<div class="row">
		<div class="col-xs-3">
			<h2>User info</h2>
			<%= attachment_image_tag current_user, :profile_image, size: "100x100", format: 'jpeg', fallback: "no_image.jpg" %>
			<table class="table">
				<tbody>
					<tr></tr>
					<tr>
						<th><label>name</label></th>
						<th><%= current_user.name %></th>
					</tr>
					<tr>
						<th><label>introduction</label></th>
						<th><%= current_user.introduction %></th>
					</tr>
				</tbody>
			</table>
			<div class="row">
				<%= link_to "", edit_user_path(current_user) , class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_18935" %>
			</div>
			<h2>New book</h2>
			<%= form_for(@book) do |f| %>
				<div class="field row">
						<label>Title</label>
						<%= f.text_field :title, class:"col-xs-12 book_title" %>
				</div>
				<div class="field row">
						<label>Opinion</label>
						<%= f.text_area :body, class:"col-xs-12 book_body"%>
				</div>
				<div class="actions row">
					<%= f.submit "Create Book", class:"btn btn-primary col-xs-12" %>
				</div>
			<% end %>
		</div>

		<div class="col-xs-9">
			<h2>Books</h2>
			<table class="table table-hover table-inverse">
				<thead>
				  	<tr>
				  		<th></th>
				  		<th>Title</th>
				  		<th>Opinion</th>
				  		<th></th>
				  		<th></th>
				  	</tr>
			  	</thead>
			  	<tbody>
			  	<% @books.each do |book| %>
			  	<tr>
			  		<td><%= link_to user_path(book.user.id) do %><%= attachment_image_tag book.user, :profile_image, size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %><% end %></td>
			  		<td><%= link_to book_path(book.id) do %><%= book.title %><% end %></td>
			  		<td><%= book.body %></td>
			  		<td id="favorite-<%= book.id %>">
			  			<%= render partial: 'favorites/favorite', locals:{ book: book } %>
			  		</td>
		  			<td><p class="comment-list bt style-2">コメント数:<%= book.post_comments.count %></p></td>
			  	</tr>
			  	<% end %>
			</table>
	  	</div>
	</div>
</div>

app/views/books/show.html.erb
<div class ="container">

	<% if @book.errors.any? %>
		<p><%= @book.errors.count %>error prohibited this obj from being saved: </p>
		<ul>
			<% @book.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	<% end %>

	<% if flash[:notice] %>
		<div class="flash"><%= flash[:notice] %></div>
	<% end %>


	<div class="row">
		<div class="col-xs-3">
			<h2>User info</h2>
			<%= attachment_image_tag @books.user, :profile_image, size: "100x100", format: 'jpeg', fallback: "no_image.jpg" %>
			<table class="table">
				<tr></tr>
				<tr>
					<th><label>name</label></th>
					<th><p><%= @books.user.name %></p></th>
				</tr>
				<tr>
					<th><label>introduction</label></th>
					<th><p><%= @books.user.introduction %></p></th>
				</tr>
			</table>
			<% if @books.user.id == current_user.id %>
				<%= link_to "", edit_user_path(@books.user), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_18898" %>
			<% end %>

			<div class="create">
				<h2>New book</h2>
				<%= form_for(@book) do |f| %>
					<div class="field row">
						<label>Title</label>
						<%= f.text_field :title, class:"col-xs-12 book_title" %>
					</div>
					<div class="field row">
						<label>Opinion</label>
						<%= f.text_area :body , class:"col-xs-12 book_body"%>
					</div>
					<div class="action row">
					<%= f.submit "Create Book", class:"btn btn-primary col-xs-12" %>
					</div>
				<% end %>
			</div>
		</div>

		<div class="col-xs-9">
			<h2>Book detail</h2>
			<table class="table table-hover table-inverse">
				<tbody>
				<tr>
					<td>
						<%= link_to user_path(@books.user) do %>
							<%= attachment_image_tag @books.user, :profile_image, size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %><br>
							<%= @books.user.name %>
						<% end %>
					</td>
					<td><%= @books.title %></td>
					<td><%= @books.body %></td>
					<% if @books.user == current_user %>
						<td>
							<%= link_to "Edit", edit_book_path %>
						</td>
						<td>
						<%= link_to "Destroy",  book_path(@books.id), method: :delete, data: {confirm: "本当に削除しますか？"} %>
						</td>
					<% else %>
					<td>
						<%= render partial: 'favorites/favorite', locals:{ book: @books } %>
					</td>
					<td><p class="comment-list bt style-2">コメント数:<%= @books.post_comments.count %></p></td>
					<% end %>
				</tr>
				</tbody>
			</table>
			<p>コメント一覧</p>
			<table class="">
				<tbody>
				<% @books.post_comments.each do |post_comment| %>
					<tr>
						<td><%= attachment_image_tag post_comment.user, :profile_image, size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %><br >
							<%= post_comment.user.name %>
						</td>
						<td><p class="comment"><%= post_comment.comment %></p></td>
						<td>
							<% if post_comment.user == current_user%>
							<%= link_to "Destroy", book_post_comment_path(post_comment.book, post_comment), method: :delete,class: "btn btn-danger pull-right red" %>
							<% end %>
						</td>
					</tr>
				<% end %>
				</tbody>
			</table>
			<div class="clearfix">
				<%= form_for [ @books, @comment] do |f| %>
					<div class="field coment">
						<label>コメント</label>
						<%= f.text_area :comment, class: "form-control" %>
					</div>
					<div class="botan">
					<%= f.submit "送信" %>
					</div>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/books/top.html.erb
<div class="container">
	<% if flash[:notice] %>
		<div class="flash"><%= flash[:notice] %></div>
	<% end %>
	<div class="row">
		<div class="top-message col-md-offset-3 col-md-6">
			<h1>welcome to <span class="glyphicon glyphicon-book"><strong>Bookers</strong></span>  !!</h1>

			<p>In <span class="glyphicon glyphicon-book"><strong>Bookers</strong></span></p>
			<p>	you can share and exchange your opinions ,inpressions ,and emotions</p>
			<p>about various books!</p>
			<div class="btn-wrapper">
			<% if user_signed_in? %>
				<div class="row">
				<p><%= link_to "Log in", users_path(params[:id]), class:"btn btn-info col-xs-10 col-xs-offset-1 sign_in" %></p>
				<p><%= link_to "Sign up", users_path(params[:id]), class:"btn btn-success col-xs-10 col-xs-offset-1 sign_up" %></p>
			<% else %>
				<p><%= link_to "Log in", new_user_session_path, class:"btn btn-info col-xs-10 col-xs-offset-1 sign_in" %></p>
				<p><%= link_to "Sign up", new_user_registration_path, class:"btn btn-success col-xs-10 col-xs-offset-1 sign_up" %></p>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/favorites/_favorite.html.erb
<div id="favorite-<%= book.id %>">
<% if book.favorited_by?(current_user) %>
    <%= link_to book_favorites_path(book.id), method: :delete, remote: true do %>
    <i class="fa fa-heart" aria-hidden="true" style="color: black;"></i>
    <%= book.favorites.count %>
    <% end %>
<% else %>
    <%= link_to book_favorites_path(book.id), method: :post, remote: true do %>
    <i class="far fa-heart" aria-hidden="true" ></i>
    <%= book.favorites.count %>
    <% end %>
<% end %>
</div>

app/views/favorites/create.js.erb
$( "#favorite-<%= @book.id %>").html("<%= j(render partial: 'favorites/favorite', locals: { book: @book })%>");

app/views/favorites/destroy.js.erb
$( "#favorite-<%= @book.id %>").html("<%= j(render partial: 'favorites/favorite', locals:{ book: @book }) %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/455412426e.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header class="navbar navbar-fixed-top navbar-inverse clearfix">
    <div class="container">
      <nav class="nav navbar-nav navbar-left">
        <span>Bookers</span>
      </nav>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li>
              <%= link_to ' Home', user_path(current_user.id), class:"glyphicon glyphicon-home home" %>
            </li>
            <li>
              <%= link_to ' Users', users_path, class:"glyphicon glyphicon-link users" %>
            </li>
            <li>
              <%= link_to ' Books', books_path,class:"glyphicon glyphicon-edit books" %>
            </li>
            <li>
              <%= link_to " logout", destroy_user_session_path, method: :delete, class:"glyphicon glyphicon-log-in logout" %>
            </li>

          <% else %>
            <li>
              <%= link_to " Home", root_path, class:"glyphicon glyphicon-home home" %></a>
            </li>
            <li>
              <%= link_to " About", home_about_path, class:"glyphicon glyphicon-link about" %>
            </li>
            <li>
              <%= link_to " sign up", new_user_registration_path, class:"glyphicon glyphicon-edit sign-up" %>
            </li>
            <li>
              <%= link_to " login", new_user_session_path, class:"glyphicon glyphicon-log-in login" %>
            </li>
          <% end %>
        </ul>
      </nav>
    </div>
  </header>

  <body>
    <div class="body cleafix">
      <%= yield %>
    </div>
  </body>

  <fotter>
    <div class="container">
      <div class="row">
        <div class="col-xs-3 col-xs-offset-9">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>
  </fotter>
</html>

app/views/users/edit.html.erb
<div class="container">

<div id="error">
	<% if @user.errors.any? %>
		<p><%= @user.errors.count %>error prohibited this obj from being saved: </p>
		<ul>
			<% @user.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	<% end %>
</div>

<h2>User info</h2>
<%= form_for(@user) do |f| %>
	<div class="field">
		<label>Name</label>
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<label>Image</label>
        <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg"%>
        <%= f.attachment_field :profile_image, placeholder: "ファイルを選択", class: "user-edit-form" %>
    </div>
    <div class="field">
		<label>Introduction</label>
		<%= f.text_area :introduction %>
	</div>
	<div class="actions">
		<%= f.submit "Update User" %>
	</div>
<% end %>
</div>

app/views/users/index.html.erb
<div class="container">
	<% if @book.errors.any? %>
		<p><%= @book.errors.count %>error prohibited this obj from being saved: </p>
		<ul>
			<% @book.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	<% end %>

	<div class="row">
		<div class="col-xs-3">
			<h2>User info</h2>
			<%= attachment_image_tag current_user, :profile_image, size: "100x100", format: 'jpeg', fallback: "no_image.jpg" %>
			<table class="table">
				<tbody>
					<tr></tr>
					<tr>
						<th><label>name</label></th>
						<th><%= current_user.name %></th>
					</tr>
					<tr>
						<th><label>introduction</label></th>
						<th><%= current_user.introduction %></th>
					</tr>
				</tbody>
			</table>
			<div class="row">
				<%= link_to "", edit_user_path(current_user) , class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_18935" %>
			</div>
			<h2>New book</h2>
			<%= form_for(@book) do |f| %>
				<div class="field row">
						<label>Title</label>
						<%= f.text_field :title, class:"col-xs-12 book_title" %>
				</div>
				<div class="field row">
						<label>Opinion</label>
						<%= f.text_area :body, class:"col-xs-12 book_body"%>
				</div>
				<div class="actions row">
					<%= f.submit "Create Book", class:"btn btn-primary col-xs-12" %>
				</div>
			<% end %>
		</div>

		<div class="col-xs-9">
			<h2>Users</h2>
			<table class="table">
				<thead>
					<tr>
						<th>image</th>
						<th>name</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
				<% @users.each do |user| %>
					<tr>
						<td>
							<%= attachment_image_tag user, :profile_image, size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %>
						</td>
						<td></td>
						<td>
							<%= user.name %>
						</td>
						<td>
							<%= link_to "Show", user_path(user) %>
						</td>
					</tr>
				<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class ="container">
	<div id="error">
		<% if @book.errors.any? %>
			<p><%= @book.errors.count %>error prohibited this obj from being saved: </p>
			<ul>
				<% @book.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
			</ul>
		<% end %>
	</div>

	<% if flash[:notice] %>
		<div class="flash notice"><%= flash[:notice] %></div>
	<% end %>


	<div class="row">
		<div class="col-xs-3">
			<h2>User info</h2>
			<div class="user">
				<%= attachment_image_tag @user, :profile_image, size: "50x50", format: 'jpeg', fallback: "no_image.jpg" %>
				<table class="table">
					<tbody>
						<tr></tr>
						<tr>
							<th><label>name</label></th>
							<th><p><%= @user.name %></p></th>
						<tr>
							<th><label>introduction</label></th>
							<th><p><%= @user.introduction %></p></th>
						</tr>
					</tbody>
				</table>
				<div class="row">
					<% if @user.id == current_user.id %>
						<%= link_to "", edit_user_path(@user), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_18898" %>
					<% end %>
				</div>
			</div>

			<div class="create">
				<h2>New book</h2>
				<%= form_for(@book) do |f| %>
					<div class="field row">
						<label>Title</label>
						<%= f.text_field :title , class:"col-xs-12 book_title"%>
					</div>
					<div class="field row">
						<label>Opinion</label>
						<%= f.text_area :body , class:"col-xs-12 book_body"%>
					</div>
					<div class="action row">
					<%= f.submit "Create Book", class:"btn btn-primary col-xs-12" %>
					</div>
				<% end %>
			</div>
		</div>

		<div class="col-xs-9">
			<h2>Books</h2>

			<table class="table table-hover table-inverse">
			  	<thaed>
			  		<tr>
			  		<th></th><th>Title</th><th>Opinion</th><th></th><th></th>
			  		</tr>
			  	</thaed>
			  	<% @books.each do |book| %>
			  	<tbody>
			  	<tr>
			  		<td><%= attachment_image_tag book.user, :profile_image, size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %></td>
			  		<td><%= link_to book_path(book.id) do %>
									<%= book.title %>
								<% end %></td>
			  		<td><%= book.body %></td>
			  		<td><p class="comment-list bt style-2">コメント数:<%= book.post_comments.count %></p></td>
			  	</tr>
			  	</tbody>
			  	<% end %>
			</table>
		</div>
	</div>
</div>